### ISSUE TITLE
Exception when trying write tiff-file with setX- and setYResolution with single long value (not a List)

### ISSUE THREAD

**Issue by Volfer** [ngageoint/tiff-java#26]
#### Version Information:

  * TIFF Java Version:  2.0.0
  * TIFF Java Source:  Central Repository
  * IDE Name & Version:  IntelliJ IDEA 2018.1.4
  * Maven Version: 
  * Java Version:  jdk_1.8.0_191
  * Platform & OS: Windows 10 x64
  * Other Relevant Libraries:

#### Expected Results:

  * What did you expect to happen?
  - Write new created TIFF-images from int array pixel values with x- and yResolution = 254 dpi.

#### Observed Results:

  * What happened instead?
  - Exception with no out tiff-file
  
  * How often does this occur?
  - Everytime if xResolution or yResolution is set.

#### Output:

  * Any logs, errors, or output messages?
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Long
	at mil.nga.tiff.TiffWriter.writeValues(TiffWriter.java:548)
	at mil.nga.tiff.TiffWriter.writeImageFileDirectories(TiffWriter.java:200)
	at mil.nga.tiff.TiffWriter.writeTiff(TiffWriter.java:137)
	at mil.nga.tiff.TiffWriter.writeTiffToBytes(TiffWriter.java:106)
	at mil.nga.tiff.TiffWriter.writeTiff(TiffWriter.java:71)

#### Steps to Reproduce:

  1. Step One
  - long xResolution = 254;
  - long yResolution = 254;

  2. Step Two
  ...
  - fileDirs.setXResolution(xResolution);
  - fileDirs.setYResolution(yResolution);
  ...

  3. Step Three
   newImage = new TIFFImage();
   writeTiff(file, newImage);

#### Relevant Code:

```java
// Code to reproduce the problem?
  long xResolution = 254;
  long yResolution = 254;

    newRaster=new Rasters(18, 11, 1, 16, TiffConstants.SAMPLE_FORMAT_UNSIGNED_INT);
      fileDirs=new FileDirectory();

      int rowsPerStrip = newRaster.calculateRowsPerStrip(TiffConstants.PLANAR_CONFIGURATION_CHUNKY);
      fileDirs.setImageWidth(inpWidth);
      fileDirs.setImageHeight(inpHeight);
      fileDirs.setBitsPerSample(bitsPerSample);
      fileDirs.setSamplesPerPixel(samplesPerPixel);
      fileDirs.setSampleFormat(TiffConstants.SAMPLE_FORMAT_UNSIGNED_INT);
      fileDirs.setRowsPerStrip(rowsPerStrip);
      fileDirs.setResolutionUnit(TiffConstants.RESOLUTION_UNIT_INCH);
      fileDirs.setXResolution(xResolution);
      fileDirs.setYResolution(yResolution);
      fileDirs.setPhotometricInterpretation(TiffConstants.PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO);
      fileDirs.setPlanarConfiguration(TiffConstants.PLANAR_CONFIGURATION_CHUNKY);
      fileDirs.setCompression(TiffConstants.COMPRESSION_NO);
      fileDirs.setWriteRasters(newRaster);

      int tmpCount = 0;
      for(int y = 0; y < inpHeight; y++){
        for(int x = 0; x < inpWidth; x++){
          newRaster.setFirstPixelSample(x, y, inpPixVals[tmpCount]);
          tmpCount++;
        }
      }
      newImage = new TIFFImage();
      newImage.add(fileDirs);
      
      File file = new File("d:\\test.tif");
      TiffWriter.writeTiff(file, newImage);
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

  - I think, the Exception occurs because the type of x- and yResolution is long while "FileDirectory.setXResolution" translates it to List<Long> (in "createSingleLongList") and then "TiffWriter.writeValues" tries to cast them to long again ( "case LONG: writer.writeUnsignedInt( (Long)value )" )

**Comment by bosborn** [comment]
Made [some fixes on the develop branch](https://github.com/ngageoint/tiff-java/commit/5a34d0714b19fe903271d9969f0352e27ef2c03c).  The xResolution and yResolution are now set as rationals ("Two LONGs: the first represents the numerator of a
fraction; the second, the denominator.").  When you set the value as a single long, a denominator of 1 is added.

[This test](https://github.com/ngageoint/tiff-java/blob/5a34d0714b19fe903271d9969f0352e27ef2c03c/src/test/java/mil/nga/tiff/TiffWriteTest.java#L98) writes and reads the created tiff.

**Comment by Volfer** [comment]
Gpood solution, thanks. Yesterday I've tried to set resolutions as a list of two long values (255, 1) and it worked, but some Image-soft also shows resolution as two values. And now everything is ok, the rational values exactly what is needed.
