### ISSUE TITLE
tiff.util.TiffException: Unsupported field type for sample format: 1, bits per sample: 1

### ISSUE THREAD

**Issue by KnIfER** [ngageoint/tiff-java#28]
Could you add support for the tiff image below ? 
It's black and white, and thus very small.

![sample image (rename to *.tif) ](https://user-images.githubusercontent.com/11593903/68767241-52d98880-065b-11ea-80cf-981c97ca1c67.png)

#### Version Information:

  * TIFF Java Version: 77a8dd626014eed7160a08b0b6cb091d29b12969
  * TIFF Java Source: Source
  * IDE Name: idea11
  * Platform: win10

#### Steps to Reproduce:
```
       TIFFImage tiffImage = TiffReader.readTiff(ByteUtils.fileToBytes(new File("abc.tif")));
       List<FileDirectory> directories = tiffImage.getFileDirectories();
       FileDirectory directory = directories.get(0);
       Rasters rasters = directory.readRasters();  //crash
```
console log:
```
Exception in thread "main" tiff.util.TiffException: Unsupported field type for sample format: 1, bits per sample: 1
	at tiff.FieldType.getFieldType(FieldType.java:189)
	at tiff.FileDirectory.getFieldTypeForSample(FileDirectory.java:1292)
	at tiff.FileDirectory.readRasters(FileDirectory.java:1119)
	at tiff.FileDirectory.readRasters(FileDirectory.java:981)
	at tiff.FileDirectory.readRasters(FileDirectory.java:933)
	at tiff.FileDirectory.readRasters(FileDirectory.java:912)
	at tiff.testtiff.main(testtiff.java:19)
```

#### Test Files:
[more_samples (first 8)](https://www.fileformat.info/format/tiff/sample/index.htm)

**Comment by bosborn** [comment]
This implementation only works for bits per samples that are divisible by full bytes.  Black and white single bits per sample images are not currently supported.

You could convert the image to color tiffs and then use the library in its current form.

Example: Rename the following file to `abc.tiff`
![abc](https://user-images.githubusercontent.com/11667761/68780183-21c56d80-05f3-11ea-96ef-bd82fba76c53.png)

TIFF Image: abc.tiff

-- File Directory --

ImageWidth (256)
SHORT (2 bytes)
Count: 1
Values: 2169

ImageLength (257)
SHORT (2 bytes)
Count: 1
Values: 931

BitsPerSample (258)
SHORT (2 bytes)
Count: 2
Values: [8, 8]

Compression (259)
SHORT (2 bytes)
Count: 1
Values: 5

PhotometricInterpretation (262)
SHORT (2 bytes)
Count: 1
Values: 1

FillOrder (266)
SHORT (2 bytes)
Count: 1
Values: 1

StripOffsets (273)
LONG (4 bytes)
Count: 1
Values: [8]

Orientation (274)
SHORT (2 bytes)
Count: 1
Values: 1

SamplesPerPixel (277)
SHORT (2 bytes)
Count: 1
Values: 2

RowsPerStrip (278)
SHORT (2 bytes)
Count: 1
Values: 931

StripByteCounts (279)
LONG (4 bytes)
Count: 1
Values: [52098]

XResolution (282)
RATIONAL (8 bytes)
Count: 1
Values: [200, 1]

YResolution (283)
RATIONAL (8 bytes)
Count: 1
Values: [200, 1]

PlanarConfiguration (284)
SHORT (2 bytes)
Count: 1
Values: 1

ResolutionUnit (296)
SHORT (2 bytes)
Count: 1
Values: 2

PageNumber (297)
SHORT (2 bytes)
Count: 2
Values: [0, 1]

Predictor (317)
SHORT (2 bytes)
Count: 1
Values: 2

ExtraSamples (338)
SHORT (2 bytes)
Count: 1
Values: [2]

-- Rasters --

Width: 2169
Height: 931
Number of Pixels: 2019339
Samples Per Pixel: 2
Bits Per Sample: [8, 8]

Pixel x = 0, y = 0: [0, 255]
Pixel x = 1084, y = 465: [0, 0]
Pixel x = 2168, y = 930: [0, 0]

**Comment by KnIfER** [comment]
@bosborn I have just found another pure java library , apache common imaging , although like imageIO,  It can't be used on android directly. But after removing and replacing lots of code ( use bitmap instead of bufferedimage ), It's working now! It's capble of loading such tiff images (multiple pixels in one byte, T6 compression) .
