### ISSUE TITLE
Extracting 16 bit integer pixels  from rasters object.

### ISSUE THREAD

**Issue by mlaprise** [ngageoint/tiff-java#30]
First of all, thx for the library. It's surprising hard to get good image library on Java/Android.

The documentation is a little bit short on details on how to access the pixels from a loaded image. When using the following snippet of code I can only get a bytes buffer using either rasters.getInterleaveValues() or rasters.getSamplesValues().

`TIFFImage tiffImage = TiffReader.readTiff(input);
List<FileDirectory> directories = tiffImage.getFileDirectories();
FileDirectory directory = directories.get(0);
Rasters rasters = directory.readRasters();`

Does it mean we need to convert this buffer into the proper integer array ourself ? Is there any other ways builtin into the library ? Would it be possible to point me to an example ? Thx !

**Comment by bosborn** [comment]
We are using it in our GeoPackage libraries to read/write GeoPackage [Tiled Gridded Coverage Data](http://www.geopackage.org/guidance/extensions/tiled_gridded_coverage_data.html).

> Tiles are encoded as a single-band image using one 32-bit floating point component per pixel.

Example Source:

* https://github.com/ngageoint/geopackage-java/blob/master/src/main/java/mil/nga/geopackage/extension/coverage/CoverageDataTiffImage.java
* https://github.com/ngageoint/geopackage-java/blob/master/src/main/java/mil/nga/geopackage/extension/coverage/CoverageDataTiff.java

**Comment by mlaprise** [comment]
Thanks for examples. I'll take a look.
